# Generated by Django 5.0.1 on 2025-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='profile_pics/User_pic.png', upload_to='profile_pics/'),
        ),
    ]
