# Generated by Django 5.0.1 on 2025-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
